service: apollo-lambda
package:
  include:
    - src/**/*
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-2
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/lambda.graphqlHandler
    memorySize: 128 # set the memory size to 128mb which is the least size for a lambda function
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-plugin-typescript
  - serverless-offline
